name: fluttervideoinapppip
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  provider: ^4.0.4
  video_player: ^0.10.8+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
